# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170419_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanbase',
            name='due_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
