# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 06:43
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLoan',
            fields=[
                ('loanbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.LoanBase')),
                ('loan_name', models.CharField(default='Auto', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.loanbase',),
        ),
        migrations.CreateModel(
            name='HouseLoan',
            fields=[
                ('loanbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.LoanBase')),
                ('loan_name', models.CharField(default='House', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.loanbase',),
        ),
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('loanbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.LoanBase')),
                ('loan_name', models.CharField(default='Mortgage', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.loanbase',),
        ),
        migrations.CreateModel(
            name='PersonalLoan',
            fields=[
                ('loanbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.LoanBase')),
                ('loan_name', models.CharField(default='Personal', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.loanbase',),
        ),
        migrations.CreateModel(
            name='StudentLoan',
            fields=[
                ('loanbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.LoanBase')),
                ('loan_name', models.CharField(default='Student', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.loanbase',),
        ),
    ]
