# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 04:20
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=1000)),
                ('loanee', models.CharField(default='', max_length=300)),
                ('payment', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('SEMI-ANNUALLY', 'SEMI-ANNUALLY'), ('ANUALLY', 'ANNUALLY')], default='MONTHLY', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=1000)),
                ('payment', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('SEMI-ANNUALLY', 'SEMI-ANNUALLY'), ('ANUALLY', 'ANNUALLY')], default='MNT', max_length=100)),
                ('loanee', models.CharField(default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=1000)),
                ('loanee', models.CharField(default='', max_length=300)),
                ('payment', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('SEMI-ANNUALLY', 'SEMI-ANNUALLY'), ('ANUALLY', 'ANNUALLY')], default='MONTHLY', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=1000)),
                ('payment', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('SEMI-ANNUALLY', 'SEMI-ANNUALLY'), ('ANUALLY', 'ANNUALLY')], default='MONTHLY', max_length=100)),
                ('loanee', models.CharField(default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=1000)),
                ('loanee', models.CharField(default='', max_length=300)),
                ('payment', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('SEMI-ANNUALLY', 'SEMI-ANNUALLY'), ('ANUALLY', 'ANNUALLY')], default='MONTHLY', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
