# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 13:04
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='autoloan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='houseloan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mortgages',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personalloan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentloan',
            name='id',
        ),
        migrations.AddField(
            model_name='autoloan',
            name='loanee',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='houseloan',
            name='loanee',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mortgages',
            name='loanee',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalloan',
            name='loanee',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentloan',
            name='loanee',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
