# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20170418_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoloan',
            name='payment',
            field=models.CharField(choices=[('MNT', 'MONTHLY'), ('SAN', 'SEMI-ANNUALLY'), ('AN', 'ANNUALLY')], default='MNT', max_length=2),
        ),
        migrations.AddField(
            model_name='houseloan',
            name='payment',
            field=models.CharField(choices=[('MNT', 'MONTHLY'), ('SAN', 'SEMI-ANNUALLY'), ('AN', 'ANNUALLY')], default='MNT', max_length=2),
        ),
        migrations.AddField(
            model_name='mortgages',
            name='payment',
            field=models.CharField(choices=[('MNT', 'MONTHLY'), ('SAN', 'SEMI-ANNUALLY'), ('AN', 'ANNUALLY')], default='MNT', max_length=2),
        ),
        migrations.AddField(
            model_name='personalloan',
            name='payment',
            field=models.CharField(choices=[('MNT', 'MONTHLY'), ('SAN', 'SEMI-ANNUALLY'), ('AN', 'ANNUALLY')], default='MNT', max_length=2),
        ),
        migrations.AddField(
            model_name='studentloan',
            name='payment',
            field=models.CharField(choices=[('MNT', 'MONTHLY'), ('SAN', 'SEMI-ANNUALLY'), ('AN', 'ANNUALLY')], default='MNT', max_length=2),
        ),
    ]
