# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20170418_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mortgages',
            new_name='Mortgage',
        ),
    ]
